# Generated by Django 4.0.4 on 2022-05-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date',
            new_name='current_date',
        ),
    ]
