# Generated by Django 4.0.4 on 2022-05-07 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
