# Generated by Django 4.0.4 on 2022-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
    ]
