# Generated by Django 4.0.4 on 2022-05-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_current_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='current_date',
            new_name='_current_date',
        ),
    ]
