# Generated by Django 4.0.4 on 2022-05-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='_current_date',
            new_name='date_added',
        ),
    ]
