# Generated by Django 4.0.4 on 2022-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_rename__current_date_car_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
