# Generated by Django 4.0.4 on 2022-05-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Ръчна', 'Ръчна'), ('Автоматична', 'Автоматична')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Ван', 'Ван'), ('Джип', 'Джип'), ('Кабрио', 'Кабрио'), ('Комби', 'Комби'), ('Купе', 'Купе'), ('Миниван', 'Миниван'), ('Пикап', 'Пикап'), ('Седан', 'Седан'), ('Стреч лимузина', 'Стреч лимузина'), ('Хечбек', 'Хечбек')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carevaluation',
            name='transmission',
            field=models.CharField(choices=[('Ръчна', 'Ръчна'), ('Автоматична', 'Автоматична')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carevaluation',
            name='type',
            field=models.CharField(choices=[('Ван', 'Ван'), ('Джип', 'Джип'), ('Кабрио', 'Кабрио'), ('Комби', 'Комби'), ('Купе', 'Купе'), ('Миниван', 'Миниван'), ('Пикап', 'Пикап'), ('Седан', 'Седан'), ('Стреч лимузина', 'Стреч лимузина'), ('Хечбек', 'Хечбек')], max_length=50),
        ),
    ]
