# Generated by Django 4.0.4 on 2022-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Station Wagon', 'Station Wagon'), ('Pickup Truck', 'Pickup Truck')], max_length=50),
        ),
    ]
