# Generated by Django 4.0.5 on 2022-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0003_car_engine_type_carevaluation_engine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carevaluation',
            name='image',
            field=models.ImageField(default=2, upload_to='dealership/images'),
            preserve_default=False,
        ),
    ]
